"""Registry 类型定义 — 枚举键."""

from enum import Enum


class RegistryKey(Enum):
    """Registry 键枚举 — 编译期类型安全."""

    # 基础设施
    EVENT_BUS = "event_bus"
    SCHEDULER_CORE = "scheduler_core"
    MESSAGE = "message"
    SITE_CACHE = "site_cache"
    SITE_ENGINE = "site_engine"
    PLUGIN_REGISTRY = "plugin_registry"
    HOOK_SYSTEM = "hook_system"
    PLUGIN_SANDBOX = "plugin_sandbox"
    MEDIA_SERVER = "media_server"

    # 业务 Service
    MEDIA_SERVICE = "media_service"
    DOWNLOADER_CORE = "downloader_core"
    INDEXER_SERVICE = "indexer_service"
    SUBSCRIBE_SERVICE = "subscribe_service"
    SEARCHER = "searcher"
    SYNC_SERVICE = "sync_service"
    SYNC_ENGINE = "sync_engine"
    RSS_TASK_SERVICE = "rss_task_service"

    # 其他 Service
    AGENT_SERVICE = "agent_service"
    APIKEY_SERVICE = "apikey_service"
    BRUSH_TASK_SERVICE = "brush_task_service"
    FILE_INDEX_SERVICE = "file_index_service"
    MEDIA_CONFIG_SERVICE = "media_config_service"
    MEDIA_INFO_SERVICE = "media_info_service"
    MEDIA_RECOGNIZER = "media_recognizer"
    RBAC_SERVICE = "rbac_service"
    SEARCH_INTENT_AGENT = "search_intent_agent"
    SITE_FAVICON_SERVICE = "site_favicon_service"
    SITE_RESOLVER = "site_resolver"
    SYSTEM_LIFECYCLE = "system_lifecycle"
    TMDB_CLIENT = "tmdb_client"
    TORRENTREMOVER_SERVICE = "torrentremover_service"
    WORDS_SERVICE = "words_service"

    # 基础设施对象（lifespan 中创建但未注册，现在补上）
    THREAD_EXECUTOR = "thread_executor"
    DOWNLOAD_MONITOR = "download_monitor"
    FILETRANSFER_SERVICE = "filetransfer_service"
    MESSAGE_QUEUE = "message_queue"

    # 轻量级 Service（lifespan 中现场构造）
    BRUSH_SERVICE = "brush_service"
    SITE_SERVICE = "site_service"
    DOWNLOAD_SERVICE = "download_service"
    FILTER_SERVICE = "filter_service"
    INDEXER_CONFIG_SERVICE = "indexer_config_service"
    MEDIA_FILE_SERVICE = "media_file_service"
    MEDIA_LIBRARY_SERVICE = "media_library_service"
    MEDIA_RECOMMENDATION_SERVICE = "media_recommendation_service"
    MEDIA_SERVER_CONFIG_SERVICE = "media_server_config_service"
    MESSAGE_CLIENT_SERVICE = "message_client_service"
    MESSAGE_SENDER_SERVICE = "message_sender_service"
    PLUGIN_FRAMEWORK_SERVICE = "plugin_framework_service"
    SCHEDULER_SERVICE = "scheduler_service"
    SEARCH_RESULT_SERVICE = "search_result_service"
    STORAGE_BACKEND_SERVICE = "storage_backend_service"
    SUBSCRIBE_CALENDAR_SERVICE = "subscribe_calendar_service"
    SUBSCRIBE_HISTORY_SERVICE = "subscribe_history_service"
    SYSTEM_CONFIG_SERVICE = "system_config_service"
    SYSTEM_INFO_SERVICE = "system_info_service"
    NET_TEST_SERVICE = "net_test_service"
    PROGRESS_SERVICE = "progress_service"
    TMDB_BLACKLIST_SERVICE = "tmdb_blacklist_service"
    TRANSFER_HISTORY_SERVICE = "transfer_history_service"
    USER_MANAGE_SERVICE = "user_manage_service"
    WEB_SEARCH_SERVICE = "web_search_service"
    BACKUP_RESTORE_SERVICE = "backup_restore_service"
    USER_RSS_SERVICE = "user_rss_service"
    CONFIG_SERVICE = "config_service"
