# -*- coding: utf-8 -*-
"""
RBAC 领域 Repository 接口（Python Protocol）
定义 RBAC（用户、角色、权限、菜单、日志）的仓储契约
"""
from typing import Any, Dict, List, Optional, Protocol, Tuple

from app.domain.entities.rbac import (
    RBACUserEntity,
    RBACRoleEntity,
    RBACPermissionEntity,
    RBACMenuEntity,
    RBACUserLoginLogEntity,
    RBACOperationLogEntity,
)


class IRBACUserRepository(Protocol):
    """RBAC用户仓储接口"""

    def get_user_by_id(self, user_id: int) -> Optional[RBACUserEntity]: ...
    def get_user_by_username(self, username: str) -> Optional[RBACUserEntity]: ...
    def get_user_by_email(self, email: str) -> Optional[RBACUserEntity]: ...
    def get_users(self, page: int = 1, page_size: int = 20, status: Optional[int] = None) -> Tuple[List[RBACUserEntity], int]: ...
    def get_all_users(self) -> List[RBACUserEntity]: ...
    def is_user_exists(self, username: str) -> bool: ...
    def is_email_exists(self, email: str) -> bool: ...
    def create_user(self, username: str, password_hash: str, email: Optional[str] = None, nickname: Optional[str] = None, is_superadmin: int = 0) -> RBACUserEntity: ...
    def update_user(self, user_id: int, **kwargs) -> bool: ...
    def update_last_login(self, user_id: int, ip: Optional[str] = None) -> bool: ...
    def delete_user(self, user_id: int) -> bool: ...
    def hard_delete_user(self, user_id: int) -> bool: ...
    def get_user_roles(self, user_id: int) -> List[RBACRoleEntity]: ...
    def assign_roles_to_user(self, user_id: int, role_ids: List[int]) -> bool: ...
    def add_role_to_user(self, user_id: int, role_id: int) -> bool: ...
    def remove_role_from_user(self, user_id: int, role_id: int) -> bool: ...


class IRBACRoleRepository(Protocol):
    """RBAC角色仓储接口"""

    def get_role_by_id(self, role_id: int) -> Optional[RBACRoleEntity]: ...
    def get_role_by_code(self, role_code: str) -> Optional[RBACRoleEntity]: ...
    def get_all_roles(self, status: Optional[int] = None) -> List[RBACRoleEntity]: ...
    def get_roles_page(self, page: int = 1, page_size: int = 20) -> Tuple[List[RBACRoleEntity], int]: ...
    def is_role_exists(self, role_code: str) -> bool: ...
    def create_role(self, role_name: str, role_code: str, description: Optional[str] = None, role_level: int = 100) -> RBACRoleEntity: ...
    def update_role(self, role_id: int, **kwargs) -> bool: ...
    def delete_role(self, role_id: int) -> bool: ...
    def get_role_permissions(self, role_id: int) -> List[RBACPermissionEntity]: ...
    def assign_permissions_to_role(self, role_id: int, permission_ids: List[int]) -> bool: ...
    def get_role_menus(self, role_id: int) -> List[RBACMenuEntity]: ...
    def assign_menus_to_role(self, role_id: int, menu_ids: List[int]) -> bool: ...


class IRBACPermissionRepository(Protocol):
    """RBAC权限仓储接口"""

    def get_permission_by_id(self, permission_id: int) -> Optional[RBACPermissionEntity]: ...
    def get_permission_by_code(self, permission_code: str) -> Optional[RBACPermissionEntity]: ...
    def get_all_permissions(self, module: Optional[str] = None, permission_type: Optional[str] = None) -> List[RBACPermissionEntity]: ...
    def get_permissions_by_codes(self, codes: List[str]) -> List[RBACPermissionEntity]: ...
    def create_permission(self, permission_name: str, permission_code: str, permission_type: str = 'api', module: Optional[str] = None, description: Optional[str] = None) -> RBACPermissionEntity: ...
    def update_permission(self, permission_id: int, **kwargs) -> bool: ...
    def delete_permission(self, permission_id: int) -> bool: ...


class IRBACMenuRepository(Protocol):
    """RBAC菜单仓储接口"""

    def get_menu_by_id(self, menu_id: int) -> Optional[RBACMenuEntity]: ...
    def get_menu_by_code(self, menu_code: str, include_hidden: bool = True) -> Optional[RBACMenuEntity]: ...
    def get_all_menus(self, status: Optional[int] = None) -> List[RBACMenuEntity]: ...
    def get_top_menus(self, include_hidden: bool = False) -> List[RBACMenuEntity]: ...
    def get_children_menus(self, parent_id: int) -> List[RBACMenuEntity]: ...
    def get_menu_tree(self, include_hidden: bool = False) -> List[Dict[str, Any]]: ...
    def get_user_menus(self, user_id: int) -> List[RBACMenuEntity]: ...
    def create_menu(self, menu_name: str, menu_code: str, parent_id: Optional[int] = None, path: Optional[str] = None, icon: Optional[str] = None, component: Optional[str] = None, sort_order: int = 0, menu_level: int = 1, permission_code: Optional[str] = None) -> RBACMenuEntity: ...
    def update_menu(self, menu_id: int, **kwargs) -> bool: ...
    def delete_menu(self, menu_id: int) -> bool: ...


class IRBACLogRepository(Protocol):
    """RBAC日志仓储接口"""

    def add_login_log(self, user_id: int, username: str, login_ip: Optional[str] = None, login_location: Optional[str] = None, user_agent: Optional[str] = None, login_type: str = 'password', login_status: int = 1, fail_reason: Optional[str] = None) -> RBACUserLoginLogEntity: ...
    def get_login_logs(self, user_id: Optional[int] = None, page: int = 1, page_size: int = 20) -> Tuple[List[RBACUserLoginLogEntity], int]: ...
    def add_operation_log(self, user_id: Optional[int] = None, username: Optional[str] = None, module: Optional[str] = None, operation_type: str = 'QUERY', description: Optional[str] = None, request_method: Optional[str] = None, request_url: Optional[str] = None, request_params: Optional[str] = None, response_data: Optional[str] = None, operation_ip: Optional[str] = None, execution_time: Optional[int] = None, operation_status: int = 1, error_msg: Optional[str] = None) -> RBACOperationLogEntity: ...
    def get_operation_logs(self, user_id: Optional[int] = None, module: Optional[str] = None, page: int = 1, page_size: int = 20) -> Tuple[List[RBACOperationLogEntity], int]: ...
