# -*- coding: utf-8 -*-
"""
RSS 种子领域 Repository 接口
"""
from typing import Optional, Protocol

from app.domain.entities.rss_torrent import RssTorrentEntity


class IRssTorrentRepository(Protocol):
    """RSS 种子仓储接口"""

    def get_by_enclosure(self, enclosure: str) -> Optional[RssTorrentEntity]: ...
    def get_by_name(self, torrent_name: str) -> Optional[RssTorrentEntity]: ...
    def insert(self, torrent_name: str, enclosure: str, type_: str, title: str,
               year: str, season: str, episode: str) -> bool: ...
    def simple_insert(self, title: str, enclosure: str) -> bool: ...
    def simple_delete(self, title: str, enclosure: Optional[str] = None) -> bool: ...
    def truncate(self) -> bool: ...
    def is_exists_by_enclosure(self, enclosure: str) -> bool: ...
    def is_exists_by_name(self, torrent_name: str, enclosure: Optional[str] = None) -> bool: ...
