#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function __fixuser {

    echo "以PUID=${PUID}，PGID=${PGID}的身份启动程序..."

    # 更改 nexus userid 和 groupid
    groupmod -o -g "$PGID" nexus
    usermod -o -u "$PUID" nexus

    # 创建目录、权限设置
    chown -R nexus:nexus "${WORKDIR}" "${HOME}" /config /etc/hosts

}

__fixuser 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"